/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngat_ccd_CCDLibrary */

#ifndef _Included_ngat_ccd_CCDLibrary
#define _Included_ngat_ccd_CCDLibrary
#ifdef __cplusplus
extern "C" {
#endif
#undef ngat_ccd_CCDLibrary_CCD_DSP_GAIN_ONE
#define ngat_ccd_CCDLibrary_CCD_DSP_GAIN_ONE 1L
#undef ngat_ccd_CCDLibrary_CCD_DSP_GAIN_TWO
#define ngat_ccd_CCDLibrary_CCD_DSP_GAIN_TWO 2L
#undef ngat_ccd_CCDLibrary_CCD_DSP_GAIN_FOUR
#define ngat_ccd_CCDLibrary_CCD_DSP_GAIN_FOUR 5L
#undef ngat_ccd_CCDLibrary_CCD_DSP_GAIN_NINE
#define ngat_ccd_CCDLibrary_CCD_DSP_GAIN_NINE 10L
#undef ngat_ccd_CCDLibrary_CCD_DSP_EXPOSURE_STATUS_NONE
#define ngat_ccd_CCDLibrary_CCD_DSP_EXPOSURE_STATUS_NONE 0L
#undef ngat_ccd_CCDLibrary_CCD_DSP_EXPOSURE_STATUS_EXPOSE
#define ngat_ccd_CCDLibrary_CCD_DSP_EXPOSURE_STATUS_EXPOSE 1L
#undef ngat_ccd_CCDLibrary_CCD_DSP_EXPOSURE_STATUS_READOUT
#define ngat_ccd_CCDLibrary_CCD_DSP_EXPOSURE_STATUS_READOUT 2L
#undef ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SINGLE
#define ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SINGLE 0L
#undef ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SPLIT_PARALLEL
#define ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SPLIT_PARALLEL 1L
#undef ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SPLIT_SERIAL
#define ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SPLIT_SERIAL 2L
#undef ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SPLIT_QUAD
#define ngat_ccd_CCDLibrary_CCD_DSP_DEINTERLACE_SPLIT_QUAD 3L
#undef ngat_ccd_CCDLibrary_CCD_INTERFACE_DEVICE_NONE
#define ngat_ccd_CCDLibrary_CCD_INTERFACE_DEVICE_NONE 0L
#undef ngat_ccd_CCDLibrary_CCD_INTERFACE_DEVICE_TEXT
#define ngat_ccd_CCDLibrary_CCD_INTERFACE_DEVICE_TEXT 1L
#undef ngat_ccd_CCDLibrary_CCD_INTERFACE_DEVICE_PCI
#define ngat_ccd_CCDLibrary_CCD_INTERFACE_DEVICE_PCI 2L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_RESET_CONTROLLER
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_RESET_CONTROLLER 1L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_HARDWARE_TEST
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_HARDWARE_TEST 2L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_TIMING_BOARD
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_TIMING_BOARD 4L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_UTILITY_BOARD
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_UTILITY_BOARD 8L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_POWER_ON
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_POWER_ON 16L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_TARGET_CCD_TEMP
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_TARGET_CCD_TEMP 32L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_GAIN
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_GAIN 64L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_IDLE
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_IDLE 128L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_DIMENSIONS
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_DIMENSIONS 256L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_DEINTERLACE
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_DEINTERLACE 512L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_ALL
#define ngat_ccd_CCDLibrary_CCD_SETUP_FLAG_ALL 1023L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_LOAD_APPLICATION
#define ngat_ccd_CCDLibrary_CCD_SETUP_LOAD_APPLICATION 0L
#undef ngat_ccd_CCDLibrary_CCD_SETUP_LOAD_FILENAME
#define ngat_ccd_CCDLibrary_CCD_SETUP_LOAD_FILENAME 1L
#undef ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_COMMANDS
#define ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_COMMANDS 0L
#undef ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_REPLIES
#define ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_REPLIES 1L
#undef ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_VALUES
#define ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_VALUES 2L
#undef ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_ALL
#define ngat_ccd_CCDLibrary_CCD_TEXT_PRINT_LEVEL_ALL 3L
/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_DSP_Get_Error_Number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1DSP_1Get_1Error_1Number
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_DSP_Get_Exposure_Status
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1DSP_1Get_1Exposure_1Status
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Exposure_Abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Exposure_1Abort
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Exposure_Abort_Readout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Exposure_1Abort_1Readout
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Exposure_Bias
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Exposure_1Bias
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Exposure_Expose
 * Signature: (ZZILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Exposure_1Expose
  (JNIEnv *, jobject, jboolean, jboolean, jint, jstring);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Exposure_Get_Error_Number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Exposure_1Get_1Error_1Number
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Exposure_Read_Out_CCD
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Exposure_1Read_1Out_1CCD
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Global_Error
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Global_1Error
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Global_Error_String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Global_1Error_1String
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Global_Initialise
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Global_1Initialise
  (JNIEnv *, jobject, jint);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Interface_Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Interface_1Close
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Interface_Open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Interface_1Open
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Setup_Abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Setup_1Abort
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Setup_Get_Error_Number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Setup_1Get_1Error_1Number
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Setup_Get_NCols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Setup_1Get_1NCols
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Setup_Get_NRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Setup_1Get_1NRows
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Setup_Get_Setup_In_Progress
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Setup_1Get_1Setup_1In_1Progress
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Setup_Setup_CCD
 * Signature: (IIILjava/lang/String;IILjava/lang/String;DIZZIIIII)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Setup_1Setup_1CCD
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint, jint, jstring, jdouble, jint, jboolean, jboolean, jint, jint, jint, jint, jint);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Temperature_Get
 * Signature: (Lngat/ccd/CCDLibraryDouble;)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Temperature_1Get
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Temperature_Get_Error_Number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Temperature_1Get_1Error_1Number
  (JNIEnv *, jobject);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Temperature_Set
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Temperature_1Set
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ngat_ccd_CCDLibrary
 * Method:    CCD_Text_Set_Print_Level
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ngat_ccd_CCDLibrary_CCD_1Text_1Set_1Print_1Level
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
