#!/bin/csh
# $Header: /home/cjm/cvs/frodospec/scripts/frodospec_plc_power_arcom_ethernet_serial,v 1.1 2009-09-02 14:07:16 cjm Exp $
# Switch the power to the Arcom Ethernet Serial server on or off
# frodospec_plc_power_arcom_ethernet_serial <on | off>
if ( $#argv < 1 ) then
	echo "frodospec_plc_power_arcom_ethernet_serial <on|off>"
	echo "This controls the power to the Arcom Ethernet Serial server."
	echo "This is used to control comms to the focus stages."
	exit 1
endif
set onoff = $1
if ( "${onoff}" == "on" ) then
	set truefalse = "true"
else if ( "${onoff}" == "off" ) then
	set truefalse = "false"
else
	echo "frodospec_plc_power_arcom_ethernet_serial <on|off>"
	exit 1
endif
if( -x /icc/bin/eip/test/i386-linux/eip_test_write_boolean ) then
	alias write_boolean '/icc/bin/eip/test/i386-linux/eip_test_write_boolean'
else
	echo "Failed to find eip_test_write_boolean."
	exit 1
endif
# configuration
set hostname = "frodospecplc"
# Power to Arcom ESS from:Frodospec Instrument Control Computer to PLC Interface Control Document v0.5 (03/10/08)
set address = "N10:0/11"
write_boolean -ip ${hostname} -a ${address} -v ${truefalse}
#
# $Log: not supported by cvs2svn $
#
