#!/bin/csh
# $Header: /home/cjm/cvs/frodospec/scripts/get_temperature,v 1.2 2007-07-19 10:48:54 cjm Exp $
if ( $#argv < 1 ) then
	echo "get_temperature <board>"
	echo "<board> should be 0 or 1."
	exit 1
endif
set board = $1
alias test_temperature '/icc/bin/frodospec/ccd/test/i386-linux/test_temperature'
test_temperature -i pci -device_pathname "/dev/astropci${board}" -get | grep 'The current temperature'
test_temperature -i pci -device_pathname "/dev/astropci${board}" -heater_adus | grep 'The current heater'
#test_temperature -i pci -heater_adus | grep 'The current heater'
#
# $Log: not supported by cvs2svn $
# Revision 1.1  2007/07/06 15:54:50  cjm
# Initial revision
#
#
