#!/bin/csh
# $Header: /home/cjm/cvs/frodospec/scripts/simple_image,v 1.3 2007-07-19 10:48:58 cjm Exp $
alias test_exposure '/icc/bin/frodospec/ccd/test/i386-linux/test_exposure'
set timing_filename = '/icc/bin/frodospec/dsp/tim.lod'
set util_filename = '/icc/bin/frodospec/dsp/util.lod'
set temperature = '-100.0'
set xsize = 2048
set ysize = 4100
if ( $#argv < 2 ) then
	echo "simple_image <board> <exposure_length> [<image filename>]"
	echo "<board> should be 0 or 1."
	echo "<exposure_length> is in milliseconds."
	exit 1
else
	set board = $1
	set exposure_length = $2
endif
if ( $#argv == 3 ) then
	set image_filename = $3
else
	set image_filename  = "/icc/tmp/Image-"`date +"%s"`".fits"
endif
echo "About to expose ${exposure_length} ms and save to ${image_filename}."
test_exposure -i pci -device_pathname "/dev/astropci${board}" -timing_filename "${timing_filename}" -utility_filename "${util_filename}"  -temperature ${temperature} -xs ${xsize} -ys ${ysize} -xb 1 -yb 1 -a left -f ${image_filename} -expose ${exposure_length}
echo "Imaged saved to ${image_filename}."
#
# $Log: not supported by cvs2svn $
# Revision 1.2  2007/07/19 10:21:13  cjm
# Added board control.
#
# Revision 1.1  2007/07/06 15:54:55  cjm
# Initial revision
#
#
